// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqkzSP10yuK4tFlRkxOhTQpIa2qNAxu8',
    appId: '1:758981298041:web:64c6cde3c38d9743e291a8',
    messagingSenderId: '758981298041',
    projectId: 'task-app-c7558',
    authDomain: 'task-app-c7558.firebaseapp.com',
    storageBucket: 'task-app-c7558.appspot.com',
    measurementId: 'G-7QJ6D60PE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxnTPxK9PVRRPXKPbeeCrFCcgV4mVxN7s',
    appId: '1:758981298041:android:f22fbcdfcd8fceafe291a8',
    messagingSenderId: '758981298041',
    projectId: 'task-app-c7558',
    storageBucket: 'task-app-c7558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBroFDoeo_joLhu5l8QAVI0ThlNXHs2R9w',
    appId: '1:758981298041:ios:c7d78f4859dccfe5e291a8',
    messagingSenderId: '758981298041',
    projectId: 'task-app-c7558',
    storageBucket: 'task-app-c7558.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );
}
